SYS_BROKER_CLIENTS_CONNECTED = "$SYS/broker/clients/connected"
SYS_BROKER_BYTES_RECEIVED = "$SYS/broker/load/bytes/received"
SYS_BROKER_BYTES_SEND = "$SYS/broker/load/bytes/sent"
SYS_BROKER_NUMBER_CLIENTS_CONNECTED = "$SYS/broker/clients/total"

TEST = "test"
PUB_KEYS_TOPIC = "PubKeys"
SEND_MESSAGE_TOPIC = "client/receive/#"
SEND_ENCRYPTED_MESSAGE = "client/encrypted/receive/"
MAXIMUM_BLOCK_SIZE = 35
INCREMENT_TRUST_VALUE = "client/trustvalue/add/"
DECREMENT_TRUST_VALUE = "client/trustvalue/decrement"
CHOOSE_MINER = "client/trustvalue/choose"
CHECK_BLOCK = "client/trustvalue/check"
TRUST_RATE = "client/trustvalue"
NEW_BLOCK = "client/block/new"
FALSE_VALIDATION = "client/trustvalue/decrement"
CORRECT_VALIDATION = "client/trustvalue/add/"
